GET http://localhost:8082
Authorization: LetMeIn
###
GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies?min_value=1
###
GET http://localhost:8082/currencies/inr
###
GET http://localhost:8082/users
Authorization: LetMeIn
###
GET http://localhost:8082/users/6607d086-719-4c26-beb1-280c9f9cbf35
###
GET http://localhost:8082/users/search?age=male
###
GET http://localhost:8082/users/search?gender=50
###
GET http://localhost:8082/users/search?q=%7B%22gender%22:%20%22male%22,%20%22age%22:%2049%7D
###
GET http://localhost:8082/users/search?gender=female&age=-1
Authorization: LetMeIn
###
GET http://localhost:8082/users/search
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{   
    "title": "Travel blog on Manali",
    "content": "manali",
    "authors": [{
        "fullName": "john doe",
        "twitterHandle": "jdoe_vlogger",
        "email": "jdoe@gmail.com",
        "image": "https://igmcdn.com/profile/1123546513.jpg"
    }]
}
###
GET http://localhost:8082/blogs
###
GET http://localhost:8082/blogs/66b3a818cee53442c2db036f
###
PATCH http://localhost:8082/blogs/66b63beec8a40a3e186c2b0c
Content-Type: application/json

{   
    "content": "very cool blog"
}
###
DELETE http://localhost:8082/blogs/66b3a07aa77d9a1bc4e16c08
###
GET http://localhost:8082/blogs/search?title=dist
###
GET http://localhost:8082/blogs/search?author=jdoe@bbc.co.uk
###
GET http://localhost:8082/blogs/search?author=jdoe@bbc.co.uk&title=lake
###
GET http://localhost:8082/blogs/search